# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'setupForm.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QSpacerItem, QTextEdit, QWidget)

class Ui_SetupForm(object):
    def setupUi(self, SetupForm):
        if not SetupForm.objectName():
            SetupForm.setObjectName(u"SetupForm")
        SetupForm.resize(1095, 892)
        self.label = QLabel(SetupForm)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 60, 111, 16))
        self.ControlFrame = QFrame(SetupForm)
        self.ControlFrame.setObjectName(u"ControlFrame")
        self.ControlFrame.setGeometry(QRect(20, 80, 461, 171))
        self.ControlFrame.setStyleSheet(u"background-color : white;")
        self.ControlFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.ControlFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.widgetScreenSetting = QWidget(self.ControlFrame)
        self.widgetScreenSetting.setObjectName(u"widgetScreenSetting")
        self.widgetScreenSetting.setGeometry(QRect(10, 90, 401, 61))
        self.widgetScreenSetting.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.horizontalLayout_2 = QHBoxLayout(self.widgetScreenSetting)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.screenconfig_label = QLabel(self.widgetScreenSetting)
        self.screenconfig_label.setObjectName(u"screenconfig_label")

        self.horizontalLayout_2.addWidget(self.screenconfig_label)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer_2)

        self.btnFullScreenOn = QPushButton(self.widgetScreenSetting)
        self.btnFullScreenOn.setObjectName(u"btnFullScreenOn")
        self.btnFullScreenOn.setMinimumSize(QSize(96, 32))

        self.horizontalLayout_2.addWidget(self.btnFullScreenOn)

        self.btnFullScreenOff = QPushButton(self.widgetScreenSetting)
        self.btnFullScreenOff.setObjectName(u"btnFullScreenOff")
        self.btnFullScreenOff.setMinimumSize(QSize(96, 32))

        self.horizontalLayout_2.addWidget(self.btnFullScreenOff)

        self.widgetSoundSetting = QWidget(self.ControlFrame)
        self.widgetSoundSetting.setObjectName(u"widgetSoundSetting")
        self.widgetSoundSetting.setGeometry(QRect(10, 20, 401, 61))
        self.widgetSoundSetting.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.horizontalLayout = QHBoxLayout(self.widgetSoundSetting)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.soundconfiglabel = QLabel(self.widgetSoundSetting)
        self.soundconfiglabel.setObjectName(u"soundconfiglabel")

        self.horizontalLayout.addWidget(self.soundconfiglabel)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.btnSoundOn = QPushButton(self.widgetSoundSetting)
        self.btnSoundOn.setObjectName(u"btnSoundOn")
        self.btnSoundOn.setMinimumSize(QSize(96, 32))

        self.horizontalLayout.addWidget(self.btnSoundOn)

        self.btnSoundOff = QPushButton(self.widgetSoundSetting)
        self.btnSoundOff.setObjectName(u"btnSoundOff")
        self.btnSoundOff.setMinimumSize(QSize(96, 32))

        self.horizontalLayout.addWidget(self.btnSoundOff)

        self.btnBack = QPushButton(SetupForm)
        self.btnBack.setObjectName(u"btnBack")
        self.btnBack.setGeometry(QRect(30, 20, 61, 32))
        self.pushButton_saveSetup = QPushButton(SetupForm)
        self.pushButton_saveSetup.setObjectName(u"pushButton_saveSetup")
        self.pushButton_saveSetup.setGeometry(QRect(940, 30, 111, 51))
        self.DectectionServerConfig = QGroupBox(SetupForm)
        self.DectectionServerConfig.setObjectName(u"DectectionServerConfig")
        self.DectectionServerConfig.setGeometry(QRect(500, 400, 351, 111))
        self.textEdit_detection_server_IP = QTextEdit(self.DectectionServerConfig)
        self.textEdit_detection_server_IP.setObjectName(u"textEdit_detection_server_IP")
        self.textEdit_detection_server_IP.setGeometry(QRect(10, 40, 220, 32))
        self.textEdit_detection_server_port = QTextEdit(self.DectectionServerConfig)
        self.textEdit_detection_server_port.setObjectName(u"textEdit_detection_server_port")
        self.textEdit_detection_server_port.setGeometry(QRect(240, 40, 96, 32))
        self.label_7 = QLabel(self.DectectionServerConfig)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 20, 31, 16))
        self.label_11 = QLabel(self.DectectionServerConfig)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(240, 20, 31, 16))
        self.cbEnableImgDetection = QCheckBox(self.DectectionServerConfig)
        self.cbEnableImgDetection.setObjectName(u"cbEnableImgDetection")
        self.cbEnableImgDetection.setGeometry(QRect(20, 80, 79, 20))
        self.Unit_1 = QGroupBox(SetupForm)
        self.Unit_1.setObjectName(u"Unit_1")
        self.Unit_1.setGeometry(QRect(20, 270, 461, 201))
        self.textEditCar1Camurl = QTextEdit(self.Unit_1)
        self.textEditCar1Camurl.setObjectName(u"textEditCar1Camurl")
        self.textEditCar1Camurl.setGeometry(QRect(10, 100, 381, 31))
        self.label_3 = QLabel(self.Unit_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 20, 31, 16))
        self.textEditCar1port = QTextEdit(self.Unit_1)
        self.textEditCar1port.setObjectName(u"textEditCar1port")
        self.textEditCar1port.setGeometry(QRect(240, 40, 111, 31))
        self.label_5 = QLabel(self.Unit_1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 80, 71, 16))
        self.textEditCar1ip = QTextEdit(self.Unit_1)
        self.textEditCar1ip.setObjectName(u"textEditCar1ip")
        self.textEditCar1ip.setGeometry(QRect(10, 40, 221, 31))
        self.label_4 = QLabel(self.Unit_1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(240, 20, 31, 16))
        self.cbUnitEnable_1 = QCheckBox(self.Unit_1)
        self.cbUnitEnable_1.setObjectName(u"cbUnitEnable_1")
        self.cbUnitEnable_1.setGeometry(QRect(390, 20, 71, 20))
        self.textEditCar1Camurl_IR = QTextEdit(self.Unit_1)
        self.textEditCar1Camurl_IR.setObjectName(u"textEditCar1Camurl_IR")
        self.textEditCar1Camurl_IR.setGeometry(QRect(10, 160, 381, 31))
        self.label_14 = QLabel(self.Unit_1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 140, 71, 16))
        self.Unit_2 = QGroupBox(SetupForm)
        self.Unit_2.setObjectName(u"Unit_2")
        self.Unit_2.setGeometry(QRect(20, 480, 461, 201))
        self.textEditCar2Camurl = QTextEdit(self.Unit_2)
        self.textEditCar2Camurl.setObjectName(u"textEditCar2Camurl")
        self.textEditCar2Camurl.setGeometry(QRect(10, 100, 381, 31))
        self.label_8 = QLabel(self.Unit_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 20, 31, 16))
        self.label_9 = QLabel(self.Unit_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(240, 20, 31, 16))
        self.textEditCar2port = QTextEdit(self.Unit_2)
        self.textEditCar2port.setObjectName(u"textEditCar2port")
        self.textEditCar2port.setGeometry(QRect(240, 40, 111, 31))
        self.textEditCar2ip = QTextEdit(self.Unit_2)
        self.textEditCar2ip.setObjectName(u"textEditCar2ip")
        self.textEditCar2ip.setGeometry(QRect(10, 40, 221, 31))
        self.label_6 = QLabel(self.Unit_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 80, 71, 16))
        self.cbUnitEnable_2 = QCheckBox(self.Unit_2)
        self.cbUnitEnable_2.setObjectName(u"cbUnitEnable_2")
        self.cbUnitEnable_2.setGeometry(QRect(390, 20, 61, 20))
        self.textEditCar2Camurl_IR = QTextEdit(self.Unit_2)
        self.textEditCar2Camurl_IR.setObjectName(u"textEditCar2Camurl_IR")
        self.textEditCar2Camurl_IR.setGeometry(QRect(10, 160, 381, 31))
        self.label_15 = QLabel(self.Unit_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 140, 71, 16))
        self.Unit_3 = QGroupBox(SetupForm)
        self.Unit_3.setObjectName(u"Unit_3")
        self.Unit_3.setGeometry(QRect(20, 690, 461, 201))
        self.textEditCar3Camurl = QTextEdit(self.Unit_3)
        self.textEditCar3Camurl.setObjectName(u"textEditCar3Camurl")
        self.textEditCar3Camurl.setGeometry(QRect(10, 100, 381, 31))
        self.label_12 = QLabel(self.Unit_3)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(10, 20, 31, 16))
        self.textEditCar3port = QTextEdit(self.Unit_3)
        self.textEditCar3port.setObjectName(u"textEditCar3port")
        self.textEditCar3port.setGeometry(QRect(240, 40, 111, 31))
        self.textEditCar3ip = QTextEdit(self.Unit_3)
        self.textEditCar3ip.setObjectName(u"textEditCar3ip")
        self.textEditCar3ip.setGeometry(QRect(10, 40, 221, 31))
        self.label_13 = QLabel(self.Unit_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(240, 20, 31, 16))
        self.label_10 = QLabel(self.Unit_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 80, 71, 16))
        self.cbUnitEnable_3 = QCheckBox(self.Unit_3)
        self.cbUnitEnable_3.setObjectName(u"cbUnitEnable_3")
        self.cbUnitEnable_3.setGeometry(QRect(390, 20, 61, 20))
        self.textEditCar3Camurl_IR = QTextEdit(self.Unit_3)
        self.textEditCar3Camurl_IR.setObjectName(u"textEditCar3Camurl_IR")
        self.textEditCar3Camurl_IR.setGeometry(QRect(10, 150, 381, 31))
        self.label_16 = QLabel(self.Unit_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 130, 71, 16))
        self.ManagerServerConfig = QGroupBox(SetupForm)
        self.ManagerServerConfig.setObjectName(u"ManagerServerConfig")
        self.ManagerServerConfig.setGeometry(QRect(500, 270, 351, 111))
        self.label_19 = QLabel(self.ManagerServerConfig)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(10, 20, 31, 16))
        self.label_20 = QLabel(self.ManagerServerConfig)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(240, 20, 31, 16))
        self.cbEnable_MMServer = QCheckBox(self.ManagerServerConfig)
        self.cbEnable_MMServer.setObjectName(u"cbEnable_MMServer")
        self.cbEnable_MMServer.setGeometry(QRect(20, 80, 79, 20))
        self.lineEdit_MMS_IP = QLineEdit(self.ManagerServerConfig)
        self.lineEdit_MMS_IP.setObjectName(u"lineEdit_MMS_IP")
        self.lineEdit_MMS_IP.setGeometry(QRect(10, 50, 211, 22))
        self.lineEdit_MMS_Port = QLineEdit(self.ManagerServerConfig)
        self.lineEdit_MMS_Port.setObjectName(u"lineEdit_MMS_Port")
        self.lineEdit_MMS_Port.setGeometry(QRect(232, 50, 91, 22))

        self.retranslateUi(SetupForm)

        QMetaObject.connectSlotsByName(SetupForm)
    # setupUi

    def retranslateUi(self, SetupForm):
        SetupForm.setWindowTitle(QCoreApplication.translate("SetupForm", u"\uc124\uc815", None))
        self.label.setText(QCoreApplication.translate("SetupForm", u"\uc81c\uc5b4\ud504\ub85c\uadf8\ub7a8\uc124\uc815", None))
        self.screenconfig_label.setText(QCoreApplication.translate("SetupForm", u"\ud654\uba74\uc124\uc815", None))
        self.btnFullScreenOn.setText(QCoreApplication.translate("SetupForm", u"\ucf2c", None))
        self.btnFullScreenOff.setText(QCoreApplication.translate("SetupForm", u"\ub054", None))
        self.soundconfiglabel.setText(QCoreApplication.translate("SetupForm", u"\uc0ac\uc6b4\ub4dc\uc124\uc815", None))
        self.btnSoundOn.setText(QCoreApplication.translate("SetupForm", u"\ucf2c", None))
        self.btnSoundOff.setText(QCoreApplication.translate("SetupForm", u"\ub054", None))
        self.btnBack.setText(QCoreApplication.translate("SetupForm", u"Back", None))
        self.pushButton_saveSetup.setText(QCoreApplication.translate("SetupForm", u"Save", None))
        self.DectectionServerConfig.setTitle(QCoreApplication.translate("SetupForm", u"Image detection Server", None))
        self.label_7.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_11.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbEnableImgDetection.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.Unit_1.setTitle(QCoreApplication.translate("SetupForm", u"1\ud638\uae30", None))
        self.label_3.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_5.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.label_4.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbUnitEnable_1.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_14.setText(QCoreApplication.translate("SetupForm", u"cam url_ir", None))
        self.Unit_2.setTitle(QCoreApplication.translate("SetupForm", u"2\ud638\uae30", None))
        self.label_8.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_9.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.label_6.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.cbUnitEnable_2.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_15.setText(QCoreApplication.translate("SetupForm", u"cam url_ir", None))
        self.Unit_3.setTitle(QCoreApplication.translate("SetupForm", u"3\ud638\uae30", None))
        self.label_12.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_13.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.label_10.setText(QCoreApplication.translate("SetupForm", u"cam url", None))
        self.cbUnitEnable_3.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
        self.label_16.setText(QCoreApplication.translate("SetupForm", u"cam url_ir", None))
        self.ManagerServerConfig.setTitle(QCoreApplication.translate("SetupForm", u"Mission Manager Server", None))
        self.label_19.setText(QCoreApplication.translate("SetupForm", u"ip", None))
        self.label_20.setText(QCoreApplication.translate("SetupForm", u"port", None))
        self.cbEnable_MMServer.setText(QCoreApplication.translate("SetupForm", u"Enable", None))
    # retranslateUi

