# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainForm.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPlainTextEdit,
    QPushButton, QSizePolicy, QWidget)
import icons_rc
import font_rc

class Ui_mainForm(object):
    def setupUi(self, mainForm):
        if not mainForm.objectName():
            mainForm.setObjectName(u"mainForm")
        mainForm.resize(1920, 1080)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainForm.sizePolicy().hasHeightForWidth())
        mainForm.setSizePolicy(sizePolicy)
        mainForm.setMinimumSize(QSize(1920, 1080))
        mainForm.setMaximumSize(QSize(1920, 1080))
        font = QFont()
        font.setFamilies([u"Arial"])
        mainForm.setFont(font)
        mainForm.setStyleSheet(u"")
        self.widgetTopBtnBar = QWidget(mainForm)
        self.widgetTopBtnBar.setObjectName(u"widgetTopBtnBar")
        self.widgetTopBtnBar.setGeometry(QRect(0, 0, 1920, 72))
        self.widgetTopBtnBar.setMinimumSize(QSize(1920, 72))
        self.widgetTopBtnBar.setStyleSheet(u"border : 1px solid black;")
        self.widgetBtnGoHome = QWidget(self.widgetTopBtnBar)
        self.widgetBtnGoHome.setObjectName(u"widgetBtnGoHome")
        self.widgetBtnGoHome.setGeometry(QRect(0, 0, 72, 72))
        sizePolicy.setHeightForWidth(self.widgetBtnGoHome.sizePolicy().hasHeightForWidth())
        self.widgetBtnGoHome.setSizePolicy(sizePolicy)
        self.widgetBtnGoHome.setMinimumSize(QSize(72, 72))
        self.widgetBtnGoHome.setStyleSheet(u"border-radius:8px;\n"
"margin:4px;")
        self.btnGoHome = QPushButton(self.widgetBtnGoHome)
        self.btnGoHome.setObjectName(u"btnGoHome")
        self.btnGoHome.setGeometry(QRect(0, 0, 72, 72))
        self.btnGoHome.setMinimumSize(QSize(72, 72))
        self.btnGoHome.setStyleSheet(u"border: none;\n"
"background-color: transparent;\n"
"")
        self.label_home = QLabel(self.widgetBtnGoHome)
        self.label_home.setObjectName(u"label_home")
        self.label_home.setGeometry(QRect(0, 0, 72, 72))
        self.label_home.setMinimumSize(QSize(72, 72))
        self.label_home.setStyleSheet(u"border: none;\n"
"")
        self.label_home.setPixmap(QPixmap(u":/\ud648.png"))
        self.label_home.setScaledContents(True)
        self.label_home.setMargin(8)
        self.label_home.raise_()
        self.btnGoHome.raise_()
        self.label_4 = QLabel(self.widgetTopBtnBar)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(72, 0, 72, 72))
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QSize(0, 0))
        self.label_4.setStyleSheet(u"border : none;")
        self.label_4.setPixmap(QPixmap(u":/\uc6b4\uc6a9\ud1b5\uc81c\uc7a5\uce58.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setMargin(24)
        self.wifiStatus = QLabel(self.widgetTopBtnBar)
        self.wifiStatus.setObjectName(u"wifiStatus")
        self.wifiStatus.setGeometry(QRect(144, 0, 72, 72))
        self.wifiStatus.setStyleSheet(u"border : none;")
        self.wifiStatus.setPixmap(QPixmap(u":/\uc640\uc774\ud30c\uc7741.png"))
        self.wifiStatus.setScaledContents(True)
        self.wifiStatus.setMargin(24)
        self.platformRobot = QLabel(self.widgetTopBtnBar)
        self.platformRobot.setObjectName(u"platformRobot")
        self.platformRobot.setGeometry(QRect(300, 0, 72, 72))
        self.platformRobot.setStyleSheet(u"border : none;")
        self.platformRobot.setPixmap(QPixmap(u":/\ud50c\ub7ab\ud3fc\ub85c\ubd07.png"))
        self.platformRobot.setScaledContents(True)
        self.platformRobot.setMargin(16)
        self.networkStatus = QLabel(self.widgetTopBtnBar)
        self.networkStatus.setObjectName(u"networkStatus")
        self.networkStatus.setGeometry(QRect(372, 0, 72, 72))
        self.networkStatus.setStyleSheet(u"border : none;")
        self.networkStatus.setPixmap(QPixmap(u":/\ub124\ud2b8\uc6cc\ud06c1.png"))
        self.networkStatus.setScaledContents(True)
        self.networkStatus.setMargin(24)
        self.batteryStatus = QLabel(self.widgetTopBtnBar)
        self.batteryStatus.setObjectName(u"batteryStatus")
        self.batteryStatus.setGeometry(QRect(445, 0, 72, 72))
        self.batteryStatus.setStyleSheet(u"border : none;")
        self.batteryStatus.setPixmap(QPixmap(u":/\ubc30\ud130\ub9ac1.png"))
        self.batteryStatus.setScaledContents(True)
        self.batteryStatus.setMargin(16)
        self.widgetTimeInfo = QWidget(self.widgetTopBtnBar)
        self.widgetTimeInfo.setObjectName(u"widgetTimeInfo")
        self.widgetTimeInfo.setGeometry(QRect(980, 0, 300, 72))
        self.widgetTimeInfo.setStyleSheet(u"border: none;\n"
"")
        self.label_8 = QLabel(self.widgetTimeInfo)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 58, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.widgetTimeInfo)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 58, 16))
        self.label_9.setFont(font)
        self.currentTime = QLabel(self.widgetTimeInfo)
        self.currentTime.setObjectName(u"currentTime")
        self.currentTime.setGeometry(QRect(90, 10, 151, 16))
        self.operationTime = QLabel(self.widgetTimeInfo)
        self.operationTime.setObjectName(u"operationTime")
        self.operationTime.setGeometry(QRect(90, 50, 101, 16))
        self.operationTime.setStyleSheet(u"")
        self.widget_11 = QWidget(self.widgetTopBtnBar)
        self.widget_11.setObjectName(u"widget_11")
        self.widget_11.setGeometry(QRect(550, 0, 288, 72))
        self.widget_11.setStyleSheet(u"border : none;")
        self.label_5 = QLabel(self.widget_11)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 96, 72))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setMinimumSize(QSize(0, 0))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(18)
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"border : none;\n"
"")
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.widget_11)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(96, 0, 96, 72))
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setFont(font1)
        self.label_6.setStyleSheet(u"border : none;\n"
"")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.widget_11)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(192, 0, 64, 72))
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"border : none;\n"
"")
        self.label_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line = QFrame(self.widget_11)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(94, 10, 2, 48))
        self.line.setStyleSheet(u"color : black; \n"
"background-color : black;")
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_2 = QFrame(self.widget_11)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(190, 10, 2, 48))
        self.line_2.setStyleSheet(u"color : black; \n"
"background-color : black;")
        self.line_2.setFrameShape(QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_10 = QLabel(self.widgetTopBtnBar)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(1320, 0, 72, 72))
        self.label_10.setStyleSheet(u"border-radius : 16px;\n"
"margin : 16px\n"
"")
        self.label_10.setPixmap(QPixmap(u":/\ud50c\ub7ab\ud3fc\ub85c\ubd07.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setMargin(0)
        self.widgetbtnSetup = QWidget(self.widgetTopBtnBar)
        self.widgetbtnSetup.setObjectName(u"widgetbtnSetup")
        self.widgetbtnSetup.setGeometry(QRect(1840, 0, 72, 72))
        self.widgetbtnSetup.setStyleSheet(u"border-radius : 8px;\n"
"margin : 4px;")
        self.label_11 = QLabel(self.widgetbtnSetup)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 0, 72, 72))
        self.label_11.setStyleSheet(u"border : none;\n"
"padding : 4px;")
        self.label_11.setPixmap(QPixmap(u":/\uc124\uc815.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setMargin(8)
        self.btnGotoSetup = QPushButton(self.widgetbtnSetup)
        self.btnGotoSetup.setObjectName(u"btnGotoSetup")
        self.btnGotoSetup.setGeometry(QRect(0, 0, 72, 72))
        self.widget_UnitNum1 = QWidget(self.widgetTopBtnBar)
        self.widget_UnitNum1.setObjectName(u"widget_UnitNum1")
        self.widget_UnitNum1.setGeometry(QRect(1430, 0, 121, 71))
        self.btnUnitChg_1 = QPushButton(self.widget_UnitNum1)
        self.btnUnitChg_1.setObjectName(u"btnUnitChg_1")
        self.btnUnitChg_1.setGeometry(QRect(0, 0, 121, 71))
        self.txUnitNuberInfo = QLabel(self.widget_UnitNum1)
        self.txUnitNuberInfo.setObjectName(u"txUnitNuberInfo")
        self.txUnitNuberInfo.setGeometry(QRect(0, 0, 121, 71))
        font2 = QFont()
        font2.setFamilies([u"D2Coding"])
        font2.setPointSize(18)
        self.txUnitNuberInfo.setFont(font2)
        self.txUnitNuberInfo.setStyleSheet(u"border : none;")
        self.txUnitNuberInfo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.txUnitNuberInfo.raise_()
        self.btnUnitChg_1.raise_()
        self.widget_UnitNum_2 = QWidget(self.widgetTopBtnBar)
        self.widget_UnitNum_2.setObjectName(u"widget_UnitNum_2")
        self.widget_UnitNum_2.setGeometry(QRect(1550, 0, 121, 71))
        self.btnUnitChg_2 = QPushButton(self.widget_UnitNum_2)
        self.btnUnitChg_2.setObjectName(u"btnUnitChg_2")
        self.btnUnitChg_2.setGeometry(QRect(0, 0, 121, 71))
        self.txUnitNuberInfo_2 = QLabel(self.widget_UnitNum_2)
        self.txUnitNuberInfo_2.setObjectName(u"txUnitNuberInfo_2")
        self.txUnitNuberInfo_2.setGeometry(QRect(0, 0, 121, 71))
        self.txUnitNuberInfo_2.setFont(font2)
        self.txUnitNuberInfo_2.setStyleSheet(u"border : none;")
        self.txUnitNuberInfo_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.txUnitNuberInfo_2.raise_()
        self.btnUnitChg_2.raise_()
        self.widget_UnitNum_3 = QWidget(self.widgetTopBtnBar)
        self.widget_UnitNum_3.setObjectName(u"widget_UnitNum_3")
        self.widget_UnitNum_3.setGeometry(QRect(1670, 0, 121, 71))
        self.btnUnitChg_3 = QPushButton(self.widget_UnitNum_3)
        self.btnUnitChg_3.setObjectName(u"btnUnitChg_3")
        self.btnUnitChg_3.setGeometry(QRect(0, 0, 121, 71))
        self.txUnitNuberInfo_3 = QLabel(self.widget_UnitNum_3)
        self.txUnitNuberInfo_3.setObjectName(u"txUnitNuberInfo_3")
        self.txUnitNuberInfo_3.setGeometry(QRect(0, 0, 121, 71))
        self.txUnitNuberInfo_3.setFont(font2)
        self.txUnitNuberInfo_3.setStyleSheet(u"border : none;")
        self.txUnitNuberInfo_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.txUnitNuberInfo_3.raise_()
        self.btnUnitChg_3.raise_()
        self.widget_UnitNum1.raise_()
        self.widget_UnitNum_2.raise_()
        self.widget_UnitNum_3.raise_()
        self.widgetBtnGoHome.raise_()
        self.label_4.raise_()
        self.wifiStatus.raise_()
        self.platformRobot.raise_()
        self.networkStatus.raise_()
        self.batteryStatus.raise_()
        self.widgetTimeInfo.raise_()
        self.widget_11.raise_()
        self.label_10.raise_()
        self.widgetbtnSetup.raise_()
        self.mainCamScreen = QWidget(mainForm)
        self.mainCamScreen.setObjectName(u"mainCamScreen")
        self.mainCamScreen.setGeometry(QRect(0, 270, 561, 311))
        self.mainCamScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.mainCamScreen_bmpLabel = QLabel(self.mainCamScreen)
        self.mainCamScreen_bmpLabel.setObjectName(u"mainCamScreen_bmpLabel")
        self.mainCamScreen_bmpLabel.setGeometry(QRect(0, 0, 561, 311))
        sizePolicy1.setHeightForWidth(self.mainCamScreen_bmpLabel.sizePolicy().hasHeightForWidth())
        self.mainCamScreen_bmpLabel.setSizePolicy(sizePolicy1)
        self.mainCamScreen_bmpLabel.setScaledContents(True)
        self.widgetZommInMainScreen = QWidget(self.mainCamScreen)
        self.widgetZommInMainScreen.setObjectName(u"widgetZommInMainScreen")
        self.widgetZommInMainScreen.setGeometry(QRect(440, 190, 101, 101))
        self.widgetZommInMainScreen.setStyleSheet(u"border:none;")
        self.btnZoomInMainScreen = QPushButton(self.widgetZommInMainScreen)
        self.btnZoomInMainScreen.setObjectName(u"btnZoomInMainScreen")
        self.btnZoomInMainScreen.setGeometry(QRect(0, 0, 128, 128))
        self.btnZoomInMainScreen.setStyleSheet(u"")
        self.label_3 = QLabel(self.widgetZommInMainScreen)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 101, 101))
        self.label_3.setPixmap(QPixmap(u":/zoom_icon.png"))
        self.label_3.setScaledContents(True)
        self.label_3.raise_()
        self.btnZoomInMainScreen.raise_()
        self.widgetBottomLeftScreen = QWidget(mainForm)
        self.widgetBottomLeftScreen.setObjectName(u"widgetBottomLeftScreen")
        self.widgetBottomLeftScreen.setGeometry(QRect(0, 580, 561, 281))
        self.widgetBottomLeftScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.widgetZoomInBottom = QWidget(self.widgetBottomLeftScreen)
        self.widgetZoomInBottom.setObjectName(u"widgetZoomInBottom")
        self.widgetZoomInBottom.setGeometry(QRect(450, 170, 96, 96))
        self.widgetZoomInBottom.setStyleSheet(u"border : none;")
        self.btnZoomInBottomScreen = QPushButton(self.widgetZoomInBottom)
        self.btnZoomInBottomScreen.setObjectName(u"btnZoomInBottomScreen")
        self.btnZoomInBottomScreen.setGeometry(QRect(0, 0, 96, 96))
        self.btnZoomInBottomScreen.setStyleSheet(u"")
        self.label_12 = QLabel(self.widgetZoomInBottom)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 0, 96, 96))
        self.label_12.setPixmap(QPixmap(u":/zoom_icon.png"))
        self.label_12.setScaledContents(True)
        self.label_12.raise_()
        self.btnZoomInBottomScreen.raise_()
        self.labelSubCamera = QLabel(self.widgetBottomLeftScreen)
        self.labelSubCamera.setObjectName(u"labelSubCamera")
        self.labelSubCamera.setGeometry(QRect(40, 20, 161, 111))
        self.labelSubCamera.raise_()
        self.widgetZoomInBottom.raise_()
        self.widgetBottomRightScreen = QWidget(mainForm)
        self.widgetBottomRightScreen.setObjectName(u"widgetBottomRightScreen")
        self.widgetBottomRightScreen.setGeometry(QRect(560, 70, 1361, 661))
        self.widgetBottomRightScreen.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;")
        self.widgetBottomRightCam = QWidget(self.widgetBottomRightScreen)
        self.widgetBottomRightCam.setObjectName(u"widgetBottomRightCam")
        self.widgetBottomRightCam.setGeometry(QRect(1220, 510, 96, 96))
        self.widgetBottomRightCam.setStyleSheet(u"border:none;")
        self.btnZoomInBottomRightScreen = QPushButton(self.widgetBottomRightCam)
        self.btnZoomInBottomRightScreen.setObjectName(u"btnZoomInBottomRightScreen")
        self.btnZoomInBottomRightScreen.setGeometry(QRect(0, 0, 96, 96))
        self.btnZoomInBottomRightScreen.setStyleSheet(u"")
        self.label_15 = QLabel(self.widgetBottomRightCam)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 96, 96))
        self.label_15.setPixmap(QPixmap(u":/zoom_icon.png"))
        self.label_15.setScaledContents(True)
        self.label_15.raise_()
        self.btnZoomInBottomRightScreen.raise_()
        self.labelBottomRightScreen = QLabel(self.widgetBottomRightScreen)
        self.labelBottomRightScreen.setObjectName(u"labelBottomRightScreen")
        self.labelBottomRightScreen.setGeometry(QRect(540, 50, 181, 91))
        self.widgetWether = QWidget(mainForm)
        self.widgetWether.setObjectName(u"widgetWether")
        self.widgetWether.setGeometry(QRect(0, 70, 560, 200))
        self.widgetWether.setStyleSheet(u"QWidget {\n"
"border: 1px solid black;\n"
"margin : 4px;\n"
"}\n"
"\n"
"QLabel  {\n"
"border : none;\n"
"    \n"
"\n"
"}\n"
"")
        self.IconWether = QLabel(self.widgetWether)
        self.IconWether.setObjectName(u"IconWether")
        self.IconWether.setGeometry(QRect(0, 50, 80, 80))
        self.IconWether.setPixmap(QPixmap(u":/\ub0a0\uc52810.png"))
        self.IconWether.setScaledContents(True)
        self.IconTemper = QLabel(self.widgetWether)
        self.IconTemper.setObjectName(u"IconTemper")
        self.IconTemper.setGeometry(QRect(210, 10, 48, 48))
        self.IconTemper.setPixmap(QPixmap(u":/\uc628\ub3c4\uacc4.png"))
        self.IconTemper.setScaledContents(True)
        self.IconWind = QLabel(self.widgetWether)
        self.IconWind.setObjectName(u"IconWind")
        self.IconWind.setGeometry(QRect(210, 140, 48, 48))
        self.IconWind.setPixmap(QPixmap(u":/\ubc14\ub78c.png"))
        self.IconWind.setScaledContents(True)
        self.IconRain = QLabel(self.widgetWether)
        self.IconRain.setObjectName(u"IconRain")
        self.IconRain.setGeometry(QRect(210, 80, 48, 48))
        self.IconRain.setPixmap(QPixmap(u":/\uac15\uc218\ud655\ub960.png"))
        self.IconRain.setScaledContents(True)
        self.IconHumidty = QLabel(self.widgetWether)
        self.IconHumidty.setObjectName(u"IconHumidty")
        self.IconHumidty.setGeometry(QRect(380, 10, 48, 48))
        self.IconHumidty.setPixmap(QPixmap(u":/\uc2b5\ub3c4.png"))
        self.IconHumidty.setScaledContents(True)
        self.IconPrecipitation = QLabel(self.widgetWether)
        self.IconPrecipitation.setObjectName(u"IconPrecipitation")
        self.IconPrecipitation.setGeometry(QRect(380, 80, 48, 48))
        self.IconPrecipitation.setPixmap(QPixmap(u":/\uac15\uc218\ub7c9.png"))
        self.IconPrecipitation.setScaledContents(True)
        self.IconWaveHeight = QLabel(self.widgetWether)
        self.IconWaveHeight.setObjectName(u"IconWaveHeight")
        self.IconWaveHeight.setGeometry(QRect(380, 140, 48, 48))
        self.IconWaveHeight.setPixmap(QPixmap(u":/\ud30c\uace0.png"))
        self.IconWaveHeight.setScaledContents(True)
        self.labelWether = QLabel(self.widgetWether)
        self.labelWether.setObjectName(u"labelWether")
        self.labelWether.setGeometry(QRect(90, 60, 108, 64))
        self.labelWether.setStyleSheet(u"qproperty-wordWrap : true;")
        self.labelWether.setTextFormat(Qt.TextFormat.PlainText)
        self.labelWether.setScaledContents(False)
        self.labelWether.setWordWrap(True)
        self.labelTemper = QLabel(self.widgetWether)
        self.labelTemper.setObjectName(u"labelTemper")
        self.labelTemper.setGeometry(QRect(260, 20, 96, 24))
        self.labelTemper.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelRain = QLabel(self.widgetWether)
        self.labelRain.setObjectName(u"labelRain")
        self.labelRain.setGeometry(QRect(260, 90, 96, 24))
        self.labelRain.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelWindy = QLabel(self.widgetWether)
        self.labelWindy.setObjectName(u"labelWindy")
        self.labelWindy.setGeometry(QRect(260, 150, 96, 24))
        self.labelWindy.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelHumidty = QLabel(self.widgetWether)
        self.labelHumidty.setObjectName(u"labelHumidty")
        self.labelHumidty.setGeometry(QRect(430, 20, 96, 24))
        self.labelHumidty.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelPrecipitation = QLabel(self.widgetWether)
        self.labelPrecipitation.setObjectName(u"labelPrecipitation")
        self.labelPrecipitation.setGeometry(QRect(430, 90, 96, 24))
        self.labelPrecipitation.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelWaveHeight = QLabel(self.widgetWether)
        self.labelWaveHeight.setObjectName(u"labelWaveHeight")
        self.labelWaveHeight.setGeometry(QRect(430, 150, 96, 24))
        self.labelWaveHeight.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.labelAreaName = QLabel(self.widgetWether)
        self.labelAreaName.setObjectName(u"labelAreaName")
        self.labelAreaName.setGeometry(QRect(20, 20, 96, 24))
        self.systemLog = QWidget(mainForm)
        self.systemLog.setObjectName(u"systemLog")
        self.systemLog.setGeometry(QRect(0, 860, 560, 221))
        self.systemLog.setStyleSheet(u"border : 1px solid black;\n"
"margin : 4px;\n"
"")
        self.edLogText = QPlainTextEdit(self.systemLog)
        self.edLogText.setObjectName(u"edLogText")
        self.edLogText.setGeometry(QRect(0, 0, 560, 221))
        self.edLogText.setStyleSheet(u"background-color: rgb(0,0,0);\n"
"color : rgb(0,255,0);")
        self.edLogText.setReadOnly(True)
        self.btnAbnormalStop = QPushButton(mainForm)
        self.btnAbnormalStop.setObjectName(u"btnAbnormalStop")
        self.btnAbnormalStop.setGeometry(QRect(560, 730, 351, 341))
        self.btnAbnormalStop.setStyleSheet(u"background-color: red;\n"
"color: white;\n"
"font-size: 24px;\n"
"font-weight: bold;")
        self.widget_opmode = QWidget(mainForm)
        self.widget_opmode.setObjectName(u"widget_opmode")
        self.widget_opmode.setGeometry(QRect(920, 730, 441, 100))
        self.widget_opmode.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.label = QLabel(self.widget_opmode)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 30, 128, 48))
        self.label.setStyleSheet(u"font-size:24px;\n"
"padding-left:16px;\n"
"border : none;")
        self.btnAutoDrv = QPushButton(self.widget_opmode)
        self.btnAutoDrv.setObjectName(u"btnAutoDrv")
        self.btnAutoDrv.setGeometry(QRect(160, 20, 120, 61))
        self.btnAutoDrv.setFont(font)
        self.btnAutoDrv.setAutoFillBackground(False)
        self.btnAutoDrv.setStyleSheet(u"font-size:24px;")
        self.btnAutoDrv.setCheckable(False)
        self.btnAutoDrv.setChecked(False)
        self.btnAutoDrv.setFlat(False)
        self.btnRemoteDrv = QPushButton(self.widget_opmode)
        self.btnRemoteDrv.setObjectName(u"btnRemoteDrv")
        self.btnRemoteDrv.setGeometry(QRect(300, 20, 120, 61))
        self.btnRemoteDrv.setStyleSheet(u"font-size:24px;\n"
"")
        self.widgetDpmode = QWidget(mainForm)
        self.widgetDpmode.setObjectName(u"widgetDpmode")
        self.widgetDpmode.setGeometry(QRect(920, 850, 441, 100))
        self.widgetDpmode.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.label_13 = QLabel(self.widgetDpmode)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 30, 128, 48))
        self.label_13.setStyleSheet(u"font-size:24px;\n"
"padding-left:16px;\n"
"border : none;")
        self.btnOpticalMode = QPushButton(self.widgetDpmode)
        self.btnOpticalMode.setObjectName(u"btnOpticalMode")
        self.btnOpticalMode.setGeometry(QRect(160, 20, 120, 61))
        self.btnOpticalMode.setStyleSheet(u"font-size:24px;")
        self.btnIRMode = QPushButton(self.widgetDpmode)
        self.btnIRMode.setObjectName(u"btnIRMode")
        self.btnIRMode.setGeometry(QRect(300, 20, 120, 61))
        self.btnIRMode.setStyleSheet(u"font-size:24px;")
        self.widg_zoom = QWidget(mainForm)
        self.widg_zoom.setObjectName(u"widg_zoom")
        self.widg_zoom.setGeometry(QRect(920, 970, 441, 100))
        self.widg_zoom.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.label_14 = QLabel(self.widg_zoom)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 20, 141, 48))
        self.label_14.setStyleSheet(u"font-size:24px;\n"
"padding-left:16px;\n"
"border : none;")
        self.btnScaleUp = QPushButton(self.widg_zoom)
        self.btnScaleUp.setObjectName(u"btnScaleUp")
        self.btnScaleUp.setGeometry(QRect(160, 20, 120, 61))
        self.btnScaleUp.setStyleSheet(u"font-size:24px;")
        self.btnScaleDown = QPushButton(self.widg_zoom)
        self.btnScaleDown.setObjectName(u"btnScaleDown")
        self.btnScaleDown.setGeometry(QRect(300, 20, 120, 61))
        self.btnScaleDown.setStyleSheet(u"font-size:24px;")
        self.widget_controlKeys = QWidget(mainForm)
        self.widget_controlKeys.setObjectName(u"widget_controlKeys")
        self.widget_controlKeys.setGeometry(QRect(1370, 730, 401, 342))
        self.widget_controlKeys.setStyleSheet(u"border : 1px solid black;\n"
"")
        self.widget = QWidget(self.widget_controlKeys)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 10, 330, 330))
        self.widget.setStyleSheet(u"border:none;")
        self.widget_keydown = QWidget(self.widget)
        self.widget_keydown.setObjectName(u"widget_keydown")
        self.widget_keydown.setGeometry(QRect(90, 200, 151, 131))
        self.widget_keydown.setStyleSheet(u"border : none;")
        self.label_keydown_normal = QLabel(self.widget_keydown)
        self.label_keydown_normal.setObjectName(u"label_keydown_normal")
        self.label_keydown_normal.setGeometry(QRect(0, 0, 151, 131))
        self.label_keydown_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\ud558_\uae30\ubcf8.png"))
        self.label_keydown_push = QLabel(self.widget_keydown)
        self.label_keydown_push.setObjectName(u"label_keydown_push")
        self.label_keydown_push.setEnabled(True)
        self.label_keydown_push.setGeometry(QRect(0, 0, 151, 131))
        self.label_keydown_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\ud558_\ub204\ub984.png"))
        self.btnKeyDown = QPushButton(self.widget_keydown)
        self.btnKeyDown.setObjectName(u"btnKeyDown")
        self.btnKeyDown.setGeometry(QRect(0, 0, 151, 131))
        self.widget_keyleft = QWidget(self.widget)
        self.widget_keyleft.setObjectName(u"widget_keyleft")
        self.widget_keyleft.setGeometry(QRect(0, 85, 120, 160))
        self.widget_keyleft.setStyleSheet(u"border : none;")
        self.label_keyleft_normal = QLabel(self.widget_keyleft)
        self.label_keyleft_normal.setObjectName(u"label_keyleft_normal")
        self.label_keyleft_normal.setGeometry(QRect(0, 0, 120, 160))
        self.label_keyleft_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc88c_\uae30\ubcf8.png"))
        self.label_keyleft_push = QLabel(self.widget_keyleft)
        self.label_keyleft_push.setObjectName(u"label_keyleft_push")
        self.label_keyleft_push.setEnabled(True)
        self.label_keyleft_push.setGeometry(QRect(0, 0, 120, 160))
        self.label_keyleft_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc88c_\ub204\ub984.png"))
        self.btnKeyLeft = QPushButton(self.widget_keyleft)
        self.btnKeyLeft.setObjectName(u"btnKeyLeft")
        self.btnKeyLeft.setGeometry(QRect(0, 0, 120, 160))
        self.widget_keyup = QWidget(self.widget)
        self.widget_keyup.setObjectName(u"widget_keyup")
        self.widget_keyup.setGeometry(QRect(90, 0, 151, 131))
        self.widget_keyup.setStyleSheet(u"border : none;")
        self.label_keyup_normal = QLabel(self.widget_keyup)
        self.label_keyup_normal.setObjectName(u"label_keyup_normal")
        self.label_keyup_normal.setGeometry(QRect(0, 0, 151, 131))
        self.label_keyup_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc0c1_\uae30\ubcf8.png"))
        self.label_keyup_push = QLabel(self.widget_keyup)
        self.label_keyup_push.setObjectName(u"label_keyup_push")
        self.label_keyup_push.setEnabled(True)
        self.label_keyup_push.setGeometry(QRect(0, 0, 151, 131))
        self.label_keyup_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc0c1_\ub204\ub984.png"))
        self.btnKeyUp = QPushButton(self.widget_keyup)
        self.btnKeyUp.setObjectName(u"btnKeyUp")
        self.btnKeyUp.setGeometry(QRect(0, 0, 151, 131))
        self.widget_keyright = QWidget(self.widget)
        self.widget_keyright.setObjectName(u"widget_keyright")
        self.widget_keyright.setGeometry(QRect(210, 85, 121, 161))
        self.widget_keyright.setStyleSheet(u"border : none;")
        self.label_keyright_normal = QLabel(self.widget_keyright)
        self.label_keyright_normal.setObjectName(u"label_keyright_normal")
        self.label_keyright_normal.setGeometry(QRect(0, 0, 151, 161))
        self.label_keyright_normal.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc6b0_\uae30\ubcf8.png"))
        self.label_keyright_push = QLabel(self.widget_keyright)
        self.label_keyright_push.setObjectName(u"label_keyright_push")
        self.label_keyright_push.setEnabled(True)
        self.label_keyright_push.setGeometry(QRect(0, 0, 151, 161))
        self.label_keyright_push.setPixmap(QPixmap(u":/\ubc29\ud5a5\ud0a4_\uc6b0_\ub204\ub984.png"))
        self.btnKeyRight = QPushButton(self.widget_keyright)
        self.btnKeyRight.setObjectName(u"btnKeyRight")
        self.btnKeyRight.setGeometry(QRect(0, 0, 151, 161))
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(150, 150, 32, 32))
        self.label_2.setStyleSheet(u"background-color:black;\n"
"border-radius : 16px;")
        self.controlOpenWidget = QWidget(mainForm)
        self.controlOpenWidget.setObjectName(u"controlOpenWidget")
        self.controlOpenWidget.setGeometry(QRect(1790, 900, 120, 48))
        self.image_unlock = QLabel(self.controlOpenWidget)
        self.image_unlock.setObjectName(u"image_unlock")
        self.image_unlock.setGeometry(QRect(80, 10, 24, 24))
        self.image_unlock.setPixmap(QPixmap(u":/\uc7a0\uae08.png"))
        self.image_unlock.setScaledContents(True)
        self.btnUnLock = QPushButton(self.controlOpenWidget)
        self.btnUnLock.setObjectName(u"btnUnLock")
        self.btnUnLock.setGeometry(QRect(0, 0, 120, 48))
        sizePolicy1.setHeightForWidth(self.btnUnLock.sizePolicy().hasHeightForWidth())
        self.btnUnLock.setSizePolicy(sizePolicy1)
        self.btnUnLock.setStyleSheet(u"background-color : transparent;")
        self.labelUnLock = QLabel(self.controlOpenWidget)
        self.labelUnLock.setObjectName(u"labelUnLock")
        self.labelUnLock.setGeometry(QRect(0, 0, 120, 48))
        self.labelUnLock.setStyleSheet(u"font-size: 20px;\n"
"padding-left : 4px;\n"
"border:1px solid black;")
        self.labelUnLock.raise_()
        self.image_unlock.raise_()
        self.btnUnLock.raise_()
        self.controLockWidget = QWidget(mainForm)
        self.controLockWidget.setObjectName(u"controLockWidget")
        self.controLockWidget.setGeometry(QRect(1790, 970, 120, 48))
        self.image_lock = QLabel(self.controLockWidget)
        self.image_lock.setObjectName(u"image_lock")
        self.image_lock.setGeometry(QRect(80, 10, 24, 24))
        self.image_lock.setPixmap(QPixmap(u":/\uc6b4\ud589.png"))
        self.image_lock.setScaledContents(True)
        self.btnLock = QPushButton(self.controLockWidget)
        self.btnLock.setObjectName(u"btnLock")
        self.btnLock.setGeometry(QRect(0, 0, 120, 48))
        self.btnLock.setStyleSheet(u"background-color:transparent;\n"
"")
        self.labelLock = QLabel(self.controLockWidget)
        self.labelLock.setObjectName(u"labelLock")
        self.labelLock.setGeometry(QRect(0, 0, 120, 48))
        self.labelLock.setStyleSheet(u"font-size:20px;\n"
"border:1px solid black;")
        self.labelLock.raise_()
        self.image_lock.raise_()
        self.btnLock.raise_()

        self.retranslateUi(mainForm)

        QMetaObject.connectSlotsByName(mainForm)
    # setupUi

    def retranslateUi(self, mainForm):
        mainForm.setWindowTitle(QCoreApplication.translate("mainForm", u"Control System", None))
        self.btnGoHome.setText("")
        self.label_home.setText("")
        self.label_4.setText("")
        self.wifiStatus.setText("")
        self.platformRobot.setText("")
        self.networkStatus.setText("")
        self.batteryStatus.setText("")
        self.label_8.setText(QCoreApplication.translate("mainForm", u"\ud604\uc7ac\uc2dc\uac04", None))
        self.label_9.setText(QCoreApplication.translate("mainForm", u"\uc6b4\uc6a9\uc2dc\uac04", None))
        self.currentTime.setText(QCoreApplication.translate("mainForm", u"YYYY-MM-DD-HH-mm", None))
        self.operationTime.setText(QCoreApplication.translate("mainForm", u"HH-mm", None))
        self.label_5.setText(QCoreApplication.translate("mainForm", u"\uc81c\uc5b4\uc7a5\uce58", None))
        self.label_6.setText(QCoreApplication.translate("mainForm", u"\uac10\uc2dc\uc7a5\uce58", None))
        self.label_7.setText(QCoreApplication.translate("mainForm", u"\uae30\ud0c0", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.btnGotoSetup.setText("")
        self.txUnitNuberInfo.setText(QCoreApplication.translate("mainForm", u"1 \ud638\uae30", None))
        self.txUnitNuberInfo_2.setText(QCoreApplication.translate("mainForm", u"2 \ud638\uae30", None))
        self.txUnitNuberInfo_3.setText(QCoreApplication.translate("mainForm", u"3 \ud638\uae30", None))
        self.mainCamScreen_bmpLabel.setText("")
        self.btnZoomInMainScreen.setText("")
        self.label_3.setText("")
        self.btnZoomInBottomScreen.setText("")
        self.label_12.setText("")
        self.labelSubCamera.setText(QCoreApplication.translate("mainForm", u"\uc601\uc0c1\uc744 \uc900\ube44\uc911\uc785\ub2c8\ub2e4.", None))
        self.btnZoomInBottomRightScreen.setText("")
        self.label_15.setText("")
        self.labelBottomRightScreen.setText(QCoreApplication.translate("mainForm", u"\uc9c0\ub3c4 \ub370\uc774\ud130\ub97c \ubd88\ub7ec\uc624\ub294\uc911", None))
        self.IconWether.setText("")
        self.IconTemper.setText("")
        self.IconWind.setText("")
        self.IconRain.setText("")
        self.IconHumidty.setText("")
        self.IconPrecipitation.setText("")
        self.IconWaveHeight.setText("")
        self.labelWether.setText(QCoreApplication.translate("mainForm", u"aaaa aaaaaaaa aaaan bbbbbb cccccc", None))
        self.labelTemper.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelRain.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelWindy.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelHumidty.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelPrecipitation.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelWaveHeight.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.labelAreaName.setText(QCoreApplication.translate("mainForm", u"TextLabel", None))
        self.btnAbnormalStop.setText(QCoreApplication.translate("mainForm", u"\ube44\uc0c1\uc815\uc9c0", None))
        self.label.setText(QCoreApplication.translate("mainForm", u"\uc6b4\uc601\ubaa8\ub4dc", None))
        self.btnAutoDrv.setText(QCoreApplication.translate("mainForm", u"\uc790\uc728", None))
        self.btnRemoteDrv.setText(QCoreApplication.translate("mainForm", u"\uc6d0\uaca9", None))
        self.label_13.setText(QCoreApplication.translate("mainForm", u"\ucd9c\ub825\ubaa8\ub4dc", None))
        self.btnOpticalMode.setText(QCoreApplication.translate("mainForm", u"\uad11\ud559", None))
        self.btnIRMode.setText(QCoreApplication.translate("mainForm", u"\uc801\uc678\uc120", None))
        self.label_14.setText(QCoreApplication.translate("mainForm", u"Zoom \uae30\ub2a5", None))
        self.btnScaleUp.setText(QCoreApplication.translate("mainForm", u"\ud655\ub300", None))
        self.btnScaleDown.setText(QCoreApplication.translate("mainForm", u"\ucd95\uc18c", None))
        self.label_keydown_normal.setText("")
        self.label_keydown_push.setText("")
        self.btnKeyDown.setText("")
        self.label_keyleft_normal.setText("")
        self.label_keyleft_push.setText("")
        self.btnKeyLeft.setText("")
        self.label_keyup_normal.setText("")
        self.label_keyup_push.setText("")
        self.btnKeyUp.setText("")
        self.label_keyright_normal.setText("")
        self.label_keyright_push.setText("")
        self.btnKeyRight.setText("")
        self.label_2.setText("")
        self.image_unlock.setText("")
        self.btnUnLock.setText("")
        self.labelUnLock.setText(QCoreApplication.translate("mainForm", u"\uc6b4\ud589", None))
        self.image_lock.setText("")
        self.btnLock.setText("")
        self.labelLock.setText(QCoreApplication.translate("mainForm", u"\uc7a0\uae08", None))
    # retranslateUi

